server:
    port: 8080
spring:
    application:
        name: chat-room-service
    jpa:
        hibernate:
            ddl-auto: update
        generate-ddl: true
        properties:
            hibernate:
                format_sql: true #To beautify or pretty print the SQL
                type:
                    preferred_uuid_jdbc_type: CHAR
            show_sql: true #show sql
            defer-datasource-initialization: true
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/chat
        username: root
        password: root

    redis:
        host: localhost
        port: 6379
    kafka:
        host: localhost
        port: 9092


logging:
    level:
        root: INFO



eureka:
    instance:
        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://127.0.0.1:8761/eureka